FROM node:22-bullseye

WORKDIR /app
COPY package*.json ./

RUN npm ci

EXPOSE 3000

ENV HOST=0.0.0.0
ENV PORT=3000
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

CMD ["npm", "run", "dev"]