import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header, Sidebar, RightBar } from '@/components';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div className="flex h-[calc(100vh-4rem)] overflow-hidden overflow-x-hidden">
          <Sidebar />
          <main className="
            flex-1 min-w-0 overflow-y-auto 
            scrollbar-custom
            ">
            {children}
          </main>
          <RightBar />
        </div>
      </body>
    </html>
  );
}
